### ISSUE TITLE
BoundsError: attempt to access 2-element Vector{Int64} at index [53]

### ISSUE THREAD

**Issue by lmiq** [SteffenPL/SpatialHashTables.jl#4]
I'm trying to run a variation of your benchmark test, but I'm getting an error in the construction of the `BoundedHashTable` structure:

```julia
julia> bht = BoundedHashTable(X, r, ones(Dim))
ERROR: BoundsError: attempt to access 2-element Vector{Int64} at index [53]
Stacktrace:
 [1] getindex
   @ SpatialHashTables ./essentials.jl:13 [inlined]
 [2] updatetable!(ht::BoundedHashTable{3, Vector{Int64}, Float64, Int64}, X::Vector{SVector{3, Float64}})
   @ SpatialHashTables ~/Downloads/SpatialHashTables.jl/src/core.jl:15
 [3] BoundedHashTable(::Vector{SVector{3, Float64}}, ::Float64, ::Vararg{Any})
   @ SpatialHashTables ~/Downloads/SpatialHashTables.jl/src/boundedhashtable.jl:94
 [4] top-level scope
   @ REPL[79]:1
```

This is the code I'm running. It has some adaptations relative to your code, specifically: use the lower level interface of CellListMap and construct a box without PBCs; generate a set of points in space with atomic density (a test I find important for the type of problem I deal); use ChunkSplitters to avoid using ThreadId.

```julia
using StaticArrays
using SpatialHashTables
using CellListMap
using Test
using BenchmarkTools
using ChunkSplitters
using Base.Threads

dist_sq(x,y) = sum(abs2, x - y)

function energy(x, y, i, j, d2, u, cutoff)
    if d2 < cutoff^2
        u += dist_sq(x,y)
    end
    return u 
end

function test_parallel(ht, X, r)
    nchunks = Threads.nthreads()
    e = zeros(nchunks)
    @sync for (irange, ichunk) in chunks(X, nchunks)
        @spawn for i in irange 
            for j in neighbours(ht, X[i], r)
                if i < j
                    e[ichunk] = energy(X[i], X[j], i, j, dist_sq(X[i], X[j]), e[ichunk], r)
                end
            end
        end
    end
    return sum(e)
end

x, _ = CellListMap.xatomic(10^4)
box = Box(limits(x), 12.0)
cl = CellList(x, box)

N = length(x)
r = box.cutoff
Dim = length(eltype(x))
X = x
bht = BoundedHashTable(X, r, ones(Dim)) # this errors
sht = SpatialHashTable(X, r, 5000)

@test test_parallel(bht, X, r) ≈ map_pairwise!((x,y,i,j,d2,u) -> energy(x,y,i,j,d2,u,box.cuoff), 0.0, box, cl)
@test test_parallel(sht, X, r) ≈ map_pairwise!((x,y,i,j,d2,u) -> energy(x,y,i,j,d2,u,box.cutoff), 0.0, box, cl)

@btime test_parallel($bht, $X, $r) 

@btime test_parallel($sht, $X, $r) 

function run_celllistmap(box,cl)
    u = CellListMap.map_pairwise!(
        (x,y,i,j,d2,u) -> energy(x,y,i,j,d2,u,box.cutoff), 
        0.0, box, cl
    ) 
    return u
end
@btime run_celllistmap($box, $cl)
```

**Comment by SteffenPL** [comment]
First of all: Thanks for checking out the package! 

I am looking into it. It might be a matter of the error message. The error is causes since the domain is between `[0,0,0]` and `[1,1,1]` but the points in `X` are outside of the range. At the moment, each time one tries to access something outside of the domain it gives a bounds error. Maybe I should improve the error message in that regard to clearly tell that one used a point outside of the range.

**Comment by SteffenPL** [comment]
You could for example do
```julia
bht = BoundedHashTable(X, r, box.computing_box...)
```
to fix the code.


The benchmark is interesting, I was in fact not sure how to construct good representative benchmarks. On my system the time was
```julia
36.939 ms (252 allocations: 34.89 KiB)
34.789 ms (252 allocations: 31.89 KiB)
2.311 ms (267 allocations: 78.58 KiB)    # CellListMap
```

**Comment by lmiq** [comment]
Oh, I see, I got confused by the use of `Dim` there. So probably what ou want there is
```julia
bht = BoundedHashTable(X, r, diag(box.input_unit_cell.matrix))
```

CellListMap provides two functions for testing.  `CellListMap.xatomic` and `CellListMap.xgalactic`. The first generates random points in 3D with a density that is the atomic density of water, and the second density of galaxies in the known universe. These functions return the coordinates and the corresponding box, which includes a sensible cutoff, so:

```julia
julia> using CellListMap, LinearAlgebra

julia> x, box = CellListMap.xgalactic(10^5);

julia> length(x)
100000

julia> box.cutoff
5.0

julia> diag(box.input_unit_cell.matrix)
3-element StaticArraysCore.SVector{3, Float64} with indices SOneTo(3):
 20.274006651911332
 20.274006651911332
 20.274006651911332

julia> x, box = CellListMap.xatomic(10^5);

julia> length(x)
100000

julia> box.cutoff
12.0

julia> diag(box.input_unit_cell.matrix)
3-element StaticArraysCore.SVector{3, Float64} with indices SOneTo(3):
 99.99999999999997
 99.99999999999997
 99.99999999999997
```

The `xgalactic` function works for `10^5` particles on, because of the typical cutoff of these calculations, which is large relative to the density of the systems. 

Note that these are internal functions, they are not guaranteed to be there forever, so please do not use them for anything your package depends (you can copy them if you will from the package source code).

Personally, I'm mostly worried about atomic systems, but I use these two functions to probe the performance for typical systems.

**Comment by lmiq** [comment]
ps: Concerning this specific issue, maybe just a better error message for the case where the particles fall outside the bounding region would do it.

**Comment by SteffenPL** [comment]
I rewrote the entire package to improve GPU performance (and too come closer to your packages performance).

The current implementation is periodic by default, which also fixes the issue of out-of-bound errors.
