### ISSUE TITLE
update CellListMap interface

### ISSUE THREAD

**Issue by lmiq** [SteffenPL/SpatialHashTables.jl#6]
Dear package author,

We have checked that your package is using `CellListMap`. The package has recently gone through an interface change, and we recommend updating your package accordingly to keep benefiting from future upgrades of `CellListMap`. 

To update you package you package, do:

- Replace `using CellListMap.PeriodicSystems` by `using CellListMap`. (or `import`)
- Replace all occurrences of `PeriodicSystems` (plural) by `CellListMap` (required if reducer!, copy_output and reset_output! were overloaded).
- Replace all occurrences of `PeriodicSystem` (singular) by `ParticleSystem`.

Set the `compat` entry of `CellListMap` to:

```
CellListMap = "0.9"
```

The interface defined in v0.9 will probably become the stable interface in a near future 1.0 version.

Note: The new `ParticleSystem` interface supports non-periodic systems, just by omitting the `unitcell` keyword.

I hope this is not much of a inconvenience. Please let me know if you need any support.

Leandro Martínez.

**Comment by SteffenPL** [comment]
Thanks, so far the dependencies are in the benchmarks only, but I'm actually working on it right now and will let you know once updated!

**Comment by SteffenPL** [comment]
I updated the benchmarks to the most current version of CellListMap (currently v9.2 probably due to some other restrictions). 

See `benchmarks/report/forcebenchmark.jl` 

(I hope the benchmarks are fair, I don't want to claim false timings.)
